### ISSUE TITLE
Feel free to borrow some code

### ISSUE THREAD

**Issue by DrZed** [Cuniq/SkypeBot#1]
https://github.com/DrZed/SkypeBot

**Comment by Cuniq** [comment]
Sure!

You can borrow too.

**Comment by DrZed** [comment]
BTW if you want add me on skype ケルドンスレイヤー and SlayerBot
Both in skype directory

**Comment by DrZed** [comment]
SlayerBot you can test your bot on if you want
me as well just give me some kind of warning XD

**Comment by DrZed** [comment]
https://github.com/LostPotatoFoundation/SkypeBot
I moved the repo
Just as well if you show a clean way to do so and want to go a head and try merging our bots into 1 and join my team :P

**Comment by Cuniq** [comment]
I will add you in 2 days because i will be offline for these days. If you want to test my bot that is really nice! You can download the jar and the config.txt from https://github.com/Cuniq/SkypeBot/releases and use it! Just write !addlistener to a chat and then you are ready to go.

I am sorry but I don't want to join a team right now. I would like to work alone for some time :) 
But if you add something new or something interesting will be happy to add in my bot too!

**Comment by DrZed** [comment]
fair enough :P also you should really use json :P

**Comment by DrZed** [comment]
Have you made sure it's launchable? http://puu.sh/j9LSs.png

**Comment by DrZed** [comment]
Main-Class: org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader You're making me use eclipse? Yuck

**Comment by DrZed** [comment]
Got it to work
I rearranged your meta inf

**Comment by DrZed** [comment]
Manifest-Version: 1.0
Main-Class: org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader
Class-Path: .
Rsrc-Class-Path: ./ skype-java-api-1.6.jar
Rsrc-Main-Class: skype.Main

**Comment by Cuniq** [comment]
thats the manifest inside the jar. Tried to double click the jar in order to open it?

**Comment by DrZed** [comment]
Yeah It didn't launch then I edited the manifest inside the jar then wala it opened

**Comment by DrZed** [comment]
also why outdated api?

**Comment by Cuniq** [comment]
1.6 is almost the same with 1.7. 1.7 has a very small fix. You can use the 1.7 if you like there are no difference

**Comment by DrZed** [comment]
k
